name: Deploy VSES site

on:
  push:
    branches: [main]   # this repo’s default branch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3   # pulls your repo into the runner

      - name: Push to web root
        run: |
          TARGET="/mnt/pool/www/vses"      # <<< change if needed
          sudo mkdir -p "$TARGET"
          sudo rsync -av --delete --chown=www-data:www-data ./ "$TARGET/"
          echo "VSES site deployed to $TARGET"