name: Deploy VSES site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Push to web root
        run: |
          TARGET="/mnt/pool/www/vses"
          mkdir -p "$TARGET"
          rsync -av --delete --chown=568:568 ./ "$TARGET/"
          echo "Site deployed to $TARGET"