name: Deploy VSES site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Push to web root
        run: |
          TARGET="/mnt/pool/www/vses"
          sudo mkdir -p "$TARGET"
          sudo rsync -av --delete --chown=www-data:www-data ./ "$TARGET/"
          echo "Site deployed to $TARGET"