name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Copy files to TrueNAS web folder
        run: |
          cp -r * /mnt/www/Vses/
