name: Deploy VSES site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rsync & python3
        run: |
          apt-get update && apt-get install -y rsync python3

      - name: Push to web root
        run: |
          TARGET="/mnt/pool/www/vses"
          mkdir -p "$TARGET"
          rsync -av --delete --chown=568:568 ./ "$TARGET/"
          echo "Site deployed to $TARGET"

      - name: Serve site on host port 8170
        run: |
          # find the first non-loopback IP of the host
          HOST_IP=$(ip route get 1 | awk '{print $7;exit}')
          python3 -m http.server 8170 --bind 0.0.0.0 --directory /mnt/pool/www/vses &
          echo "🚀  Site now live at http://$HOST_IP:8170"